// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed
// by a MIT license that can be found in the LICENSE file.
//
// Written by Changkun Ou <changkun.de>

package clipboard

import (
	"context"
	"slices"
)

// Sensitive reports whether the application that put the current content on
// the clipboard marked it as sensitive: not to be shown, kept or shared.
// Password managers mark the passwords they copy this way, and a clipboard
// manager, a history, or a tool that syncs the clipboard between machines
// should leave such content alone.
//
//	if secret, _ := clipboard.Sensitive(ctx); secret {
//		return // do not keep or upload it
//	}
//
// The marker is a platform convention:
//
//   - macOS: the org.nspasteboard.ConcealedType or TransientType pasteboard
//     type (nspasteboard.org);
//   - Windows: the ExcludeClipboardContentFromMonitorProcessing format, or
//     CanIncludeInClipboardHistory or CanUploadToCloudClipboard set to 0;
//   - X11 and Wayland: the x-kde-passwordManagerHint target, set by KeePassXC
//     and KDE.
//
// iOS, Android and the browser have no such convention that this package can
// read, and report ErrUnsupported rather than a confident false.
//
// Values from Watch carry the same answer in Data.Sensitive. Pass FromPrimary
// to ask about the primary selection.
func Sensitive(ctx context.Context, opts ...Option) (bool, error) {
	if err := ctx.Err(); err != nil {
		return false, err
	}
	lock.Lock()
	defer lock.Unlock()
	return sensitive(ctx, newConfig(opts).sel)
}

// darwinSensitiveTypes are the pasteboard types that mark content as
// sensitive, from nspasteboard.org. AutoGeneratedType is a marker too, but it
// says who made the content, not that it is secret.
var darwinSensitiveTypes = []string{
	"org.nspasteboard.ConcealedType",
	"org.nspasteboard.TransientType",
}

// x11SensitiveTarget marks content as sensitive on X11 and Wayland. Its value
// is "secret"; nothing sets it for anything else.
const x11SensitiveTarget = "x-kde-passwordManagerHint"

// windowsExcludeFormat's presence marks content as sensitive on Windows.
const windowsExcludeFormat = "ExcludeClipboardContentFromMonitorProcessing"

// windowsOptOutFormats mark content as sensitive when their DWORD value is 0.
var windowsOptOutFormats = []string{"CanIncludeInClipboardHistory", "CanUploadToCloudClipboard"}

// containsAny reports whether names holds any of markers.
func containsAny(names []string, markers ...string) bool {
	for _, m := range markers {
		if slices.Contains(names, m) {
			return true
		}
	}
	return false
}
