# Copyright 2021 The golang.design Initiative Authors.
# All rights reserved. Use of this source code is governed
# by a MIT license that can be found in the LICENSE file.
#
# Written by Changkun Ou <changkun.de>

name: clipboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  platform_test:
    env:
      DISPLAY: ':0.0'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Install and run dependencies (xvfb libx11-dev)
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt update
        sudo apt install -y xvfb libx11-dev libegl1-mesa-dev libgles2-mesa-dev
        Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>&1 &
        # Wait for Xvfb
        MAX_ATTEMPTS=120 # About 60 seconds
        COUNT=0
        echo -n "Waiting for Xvfb to be ready..."
        while ! xdpyinfo -display "${DISPLAY}" >/dev/null 2>&1; do
          echo -n "."
          sleep 0.50s
          COUNT=$(( COUNT + 1 ))
          if [ "${COUNT}" -ge "${MAX_ATTEMPTS}" ]; then
            echo "  Gave up waiting for X server on ${DISPLAY}"
            exit 1
          fi
        done
        echo "Done - Xvfb is ready!"

    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.17.x'

    - name: Build
      run: |
        go build

    - name: Run Tests
      run: |
        go test -v -covermode=atomic ./...